include_directories("${PROJECT_SOURCE_DIR}/7kyu/include")

add_library(7kyu src/jumbler.cpp
                 src/redacted.cpp
                 src/findLineup.cpp
                 src/sumOfABeach.cpp
                 src/tramCapacity.cpp
                 src/fixStringCase.cpp
                 src/smoothNumbers.cpp
                 src/convertTheScore.cpp
                 src/countCodePoints.cpp
                 src/leonardoNumbers.cpp
                 src/offloadYourWork.cpp
                 src/cigarStringsEasy.cpp
                 src/queueTimeCounter.cpp
                 src/subArrayElementsSum.cpp
                 src/removeDuplicateWords.cpp
                 src/everyPossibleSumOfTwoDigits.cpp
                 src/stringPacketBasedCommunication.cpp
                 )
